stages:
 - build

variables:
  DOCKER_REPOSITORY=atarax
  WEBSERVER_IMAGE=bodystats-nginx

build_webserver:
  image: docker
  stage: build
  script:
  - docker login -u ${DOCKERHUB_USER} -P ${DOCKERHUB_PASSWORD}
  - docker build -t ${DOCKER_REPOSITORY}/${WEBSERVER_IMAGE} app/nginx