stages:
 - build

variables:
  DOCKER_REPOSITORY: atarax
  WEBSERVER_IMAGE: bodystats-nginx

build webserver:
  image: docker
  stage: build
  script:
  - docker login -u ${DOCKERHUB_USER} -p ${DOCKERHUB_PASSWORD}
  - docker build -t ${DOCKER_REPOSITORY}/${WEBSERVER_IMAGE} app/nginx