stages:
 - build
 - deploy

variables:
  DOCKER_REPOSITORY: atarax
  WEBSERVER_IMAGE: bodystats-nginx

build webserver:
  image: docker
  stage: build
  script:
  - docker login -u ${DOCKERHUB_USER} -p ${DOCKERHUB_PASSWORD}
  - docker build -t ${DOCKER_REPOSITORY}/${WEBSERVER_IMAGE}:${CI_COMMIT_REF_NAME} app/nginx
  - docker push ${DOCKER_REPOSITORY}/${WEBSERVER_IMAGE}

deploy staging:
  image: atarax/kubernetes-toolbox
  stage: deploy
  script:
  - docker login -u ${DOCKERHUB_USER} -p ${DOCKERHUB_PASSWORD}
