stages:
 - build
 - deploy
 - release

variables:
  DOCKER_REPOSITORY: atarax
  WEBSERVER_IMAGE: bodystats-nginx

build webserver:
  image: docker
  stage: build
  script:
  - docker login -u ${DOCKERHUB_USER} -p ${DOCKERHUB_PASSWORD}
  - docker build -t ${DOCKER_REPOSITORY}/${WEBSERVER_IMAGE}:${CI_REF_NAME} app/nginx

push images:
  image: docker
  stage: deploy
  script:
  - docker login -u ${DOCKERHUB_USER} -p ${DOCKERHUB_PASSWORD}
  - docker push ${DOCKER_REPOSITORY}/${WEBSERVER_IMAGE}

release staging:
  image: atarax/kubernetes-toolbox
  stage: release
  script:
  - docker login -u ${DOCKERHUB_USER} -p ${DOCKERHUB_PASSWORD}
