apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: gitlab-deployment
spec:
  selector:
    matchLabels:
      app: gitlab
  replicas: 1 
  template: 
    metadata:
      labels:
        app: gitlab
    spec:
      containers:
      - name: gitlab
        image: gitlab/gitlab-ce:10.4.0-rc8.ce.0
        ports:
        - containerPort: 80
        - containerPort: 443
        - containerPort: 22
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: gitlab
  name: gitlab
  namespace: default
spec:
  ports:
  - name: port-1
    nodePort: 31391
    port: 80
    protocol: TCP
    targetPort: 80
  - name: port-2
    nodePort: 30109
    port: 443
    protocol: TCP
    targetPort: 443
  - name: port-3
    nodePort: 32387
    port: 22
    protocol: TCP
    targetPort: 22
  selector:
    app: gitlab
  type: LoadBalancer
